#!/usr/bin/env bash
# install-consumer.sh — setup bmad-harness-plugin ở phía consumer.
#
# Tải tarball từ GitHub release → extract → tạo config skeleton (nếu thiếu)
# → in instructions enable plugin qua settings.json.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/tantai-bic/qa-harness/main/scripts/install-consumer.sh | bash
#
# Hoặc download + run:
#   curl -fsSL -o install-consumer.sh https://raw.githubusercontent.com/tantai-bic/qa-harness/main/scripts/install-consumer.sh
#   bash install-consumer.sh [version] [install-dir]
#
# Defaults:
#   version     = latest (resolve qua gh api)
#   install-dir = $HOME/.qa-harness

set -euo pipefail

REPO="tantai-bic/qa-harness"
VERSION="${1:-latest}"
INSTALL_DIR="${2:-$HOME/.qa-harness}"
CONSUMER_DIR="$PWD"

echo "═══ qa-harness consumer setup ═══"
echo "  Repo:         $REPO"
echo "  Version:      $VERSION"
echo "  Install dir:  $INSTALL_DIR"
echo "  Consumer:     $CONSUMER_DIR"
echo ""

# ─── 1. Resolve version ────────────────────────────────────────────────────
if [[ "$VERSION" == "latest" ]]; then
  echo "→ Resolve latest version..."
  if command -v gh >/dev/null 2>&1; then
    VERSION=$(gh release list --repo "$REPO" --limit 1 --json tagName --jq '.[0].tagName' 2>/dev/null || echo "")
  fi
  if [[ -z "$VERSION" ]]; then
    # Fallback: GitHub API
    VERSION=$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" 2>/dev/null | grep -oE '"tag_name"\s*:\s*"[^"]+"' | head -1 | sed 's/.*"\([^"]*\)"/\1/')
  fi
  if [[ -z "$VERSION" ]]; then
    echo "❌ Không tìm được latest version. Specify thủ công: bash $0 v1.0.1" >&2
    exit 1
  fi
  echo "  → Latest = $VERSION"
fi

# Strip leading 'v' for filename
VER_NO_V="${VERSION#v}"
ASSET="bmad-harness-plugin-${VER_NO_V}.tgz"
URL="https://github.com/${REPO}/releases/download/${VERSION}/${ASSET}"

# ─── 2. Download tarball ──────────────────────────────────────────────────
TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT

echo ""
echo "→ Download $ASSET..."
# Repo có thể private → asset cần auth. Ưu tiên `gh` CLI (đã login),
# fallback GITHUB_TOKEN env, cuối cùng anonymous curl (chỉ public repo).
DL_OK=0
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if gh release download "$VERSION" --repo "$REPO" --pattern "$ASSET" --output "$TMP/$ASSET" 2>/dev/null; then
    DL_OK=1
  fi
fi
if [[ $DL_OK -eq 0 ]] && [[ -n "${GITHUB_TOKEN:-}" ]]; then
  if curl -fsSL -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/octet-stream" \
       -o "$TMP/$ASSET" \
       "https://api.github.com/repos/$REPO/releases/assets/$(gh api repos/$REPO/releases/tags/$VERSION --jq ".assets[] | select(.name==\"$ASSET\") | .id" 2>/dev/null)" 2>/dev/null; then
    DL_OK=1
  fi
fi
if [[ $DL_OK -eq 0 ]]; then
  if curl -fsSL -o "$TMP/$ASSET" "$URL" 2>/dev/null; then
    DL_OK=1
  fi
fi
if [[ $DL_OK -eq 0 ]]; then
  echo "❌ Download failed: $URL" >&2
  echo "   Repo có thể private. Setup gh CLI:" >&2
  echo "     gh auth login" >&2
  echo "   HOẶC set GITHUB_TOKEN env var có scope 'repo'." >&2
  exit 1
fi
SIZE=$(du -h "$TMP/$ASSET" | cut -f1)
echo "  ✓ $SIZE"

# ─── 3. Extract ───────────────────────────────────────────────────────────
echo ""
echo "→ Extract → $INSTALL_DIR..."
if [[ -d "$INSTALL_DIR" ]]; then
  echo "  ⚠ $INSTALL_DIR đã tồn tại — backup → ${INSTALL_DIR}.bak.$(date +%s)"
  mv "$INSTALL_DIR" "${INSTALL_DIR}.bak.$(date +%s)"
fi
mkdir -p "$INSTALL_DIR"
tar -xzf "$TMP/$ASSET" -C "$INSTALL_DIR"
echo "  ✓ Extracted $(find "$INSTALL_DIR" -type f | wc -l) files"

# Verify plugin manifest
if [[ ! -f "$INSTALL_DIR/.claude-plugin/plugin.json" ]]; then
  echo "❌ Invalid bundle — không thấy .claude-plugin/plugin.json" >&2
  exit 1
fi

# ─── 4. Create consumer config skeleton (nếu chưa có) ─────────────────────
echo ""
echo "→ Check consumer setup ở $CONSUMER_DIR..."

CONFIG_PATH="$CONSUMER_DIR/_bmad/bmm/config.yaml"
if [[ ! -f "$CONFIG_PATH" ]]; then
  echo "  ⚠ Thiếu $CONFIG_PATH — tạo skeleton..."
  mkdir -p "$(dirname "$CONFIG_PATH")"
  cat > "$CONFIG_PATH" <<YAML
# BMM Module Configuration — auto-generated by install-consumer.sh
project_name: $(basename "$CONSUMER_DIR")
user_name: $(whoami)
communication_language: vietnamese
document_output_language: vietnamese
output_folder: "{project-root}/_bmad-output"
user_skill_level: beginner
planning_artifacts: "{project-root}/_bmad-output/project-planning-artifacts"
implementation_artifacts: "{project-root}/_bmad-output/implementation-artifacts"
project_knowledge: "{project-root}/docs"
tea_use_mcp_enhancements: true
tea_use_playwright_utils: true
YAML
  echo "    ✓ Created $CONFIG_PATH — review + customize trước khi dùng"
else
  echo "  ✓ $CONFIG_PATH đã có"
fi

ENV_PATH="$CONSUMER_DIR/.env"
if [[ ! -f "$ENV_PATH" ]]; then
  echo "  ⚠ Thiếu .env (optional cho Langfuse)"
  cat > "$ENV_PATH.example" <<ENV
LANGFUSE_HOST=https://cloud.langfuse.com
LANGFUSE_PUBLIC_KEY=pk-lf-xxxx
LANGFUSE_SECRET_KEY=sk-lf-xxxx
ENV
  echo "    ✓ Created .env.example — copy thành .env + fill credentials nếu cần"
fi

# ─── 5. Print enable instructions ─────────────────────────────────────────
cat <<EOF

═══ ✅ Plugin installed ═══

Plugin path: $INSTALL_DIR
Version:     $VERSION

▼ ENABLE plugin (3 cách):

[A] Permanent — edit ~/.claude/settings.json:
{
  "enabledPlugins": {
    "bmad-harness-plugin@local": true
  },
  "extraKnownMarketplaces": {
    "local": {
      "type": "local",
      "path": "$INSTALL_DIR"
    }
  }
}

[B] Ad-hoc — mỗi lần chạy:
  cd $CONSUMER_DIR
  claude --plugin-dir "$INSTALL_DIR"

[C] GitHub marketplace (no local install — pull mới mỗi session):
{
  "enabledPlugins": { "bmad-harness-plugin@qa-harness": true },
  "extraKnownMarketplaces": {
    "qa-harness": { "type": "github", "repository": "$REPO" }
  }
}

▼ VERIFY:
  cd $CONSUMER_DIR
  LANGFUSE_DEBUG=1 claude --debug hooks --plugin-dir "$INSTALL_DIR"
  # /plugin list                                  → bmad-harness-plugin: enabled
  # /bmad-harness-plugin:bmad:bmm:agents:dev      → menu Amelia ≤250 tokens

▼ UPDATE:
  bash $0 latest "$INSTALL_DIR"
EOF
